import queue

Nomor_Atrian = str(input("Masukan Nomor Antiran : "))
Nama_Pasien = str(input("Masukan Nama Pasien : "))
Umur = str(input("Masukan Umur Pasien : "))
no_hp = str(input("Masukan No HP : "))
Alamat = str(input("Masukan Alamat : "))
Poli = str(input("Masukan Poli : "))
Jenis_Layanan = str(input("Masukan Jenis Layanan : "))
Suhu_Badan = float(input("Masukan Suhu Badan : "))
Berat_Badan = float(input("Masukan Berat Badan : "))
Keluhan = str(input("Masukan Keluhan : "))
tanggal = str(input("Masukan tanggal : "))
bulan = str(input("Masukan bulan : "))
tahun = str(input("Masukan tahun : "))
Admin = str(input("Masukan admin : "))

print('Mikro Health')
print("Klinik Mikro Health")
print("Jl. Thamrin 125 Binjai, Medan - Sumatera Utara")
print("==============================================")
print("Nomor Antrian \t:", Nomor_Atrian)
print("PASIEN \t \t:", Nama_Pasien)
print("UMUR PASIEN \t:", Umur)
print("NO. HP \t \t:", no_hp )
print("ALAMAT \t \t:", Alamat )
print("Poli TUJUAN \t:", Poli )
print("JENIS LAYANAN \t:", Jenis_Layanan )
print("SUHU BADAN \t:", float(Suhu_Badan) )
print("BERAT BADAN \t:", Berat_Badan )
print("KELUHAN \t:", Keluhan )
print("==============================================")
print("Binjai, ", tanggal, bulan, tahun)
print("\n \n")
print(Admin)

# TTD Orang ganteng